on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies and Publish if Necessary
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine build requests
          
          # Define the current version
          current_version="0.0.3"
          echo "Current version: $current_version"
          
          # Use Python to fetch the previous version from PyPI
          previous_version=$(python -c "import requests; response = requests.get('https://pypi.org/pypi/kairyou/json'); print(response.json()['info']['version'] if response.ok else '0.0.0')")
          echo "Previous version on PyPI: $previous_version"
          
          # Compare the current version with the previous version
          if [ "$current_version" != "$previous_version" ]; then
            echo "Version difference detected, proceeding with build and publish."
            
            # Build the package
            python -m build
            
            # Publish the package to PyPI
            python -m twine upload dist/* --username __token__ --password $TWINE_PASSWORD
          else
            echo "No version difference detected, skipping build and publish."
