on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine build

      - name: Determine Current and Previous Version
        id: version_check
        run: |
          current_version="0.0.3" # Manually set your current version here
          echo "Current version: $current_version"
          # Install twine if not already installed
          python -m pip install twine
          # Fetch the previous version from PyPI
          previous_version=$(twine search kairyou | grep -oP '(?<=kairyou )\d+\.\d+\.\d+' || echo "0.0.0")
          echo "Previous version on PyPI: $previous_version"
          # Compare versions and set an environment variable for conditional checks
          if [ "$current_version" != "$previous_version" ]; then
            echo "VERSIONS_DIFFER=1" >> $GITHUB_ENV
          else
            echo "VERSIONS_DIFFER=0" >> $GITHUB_ENV
          fi

      - name: Build distribution files
        if: env.VERSIONS_DIFFER == '1'
        run: |
          python -m build

      - name: Publish to PyPI
        if: env.VERSIONS_DIFFER == '1'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*
