on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check current version
        id: version
        run: |
          current_version=$(python -c "from src.kairyou.kairyou import __version__; print(__version__)")
          echo "Current version: $current_version"
          echo "::set-output name=current_version::$current_version"

      - name: Fetch previous version from PyPI
        id: previous_version
        run: |
          previous_version=$(twine search kairyou | grep -oP '(?<=kairyou )\d+\.\d+\.\d+')
          echo "Previous version on PyPI: $previous_version"
          echo "::set-output name=previous_version::$previous_version"
          
      - name: Build distribution files
        if: steps.version.outputs.current_version != steps.previous_version.outputs.previous_version
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
          
      - name: Publish to PyPI
        if: steps.version.outputs.current_version != steps.previous_version.outputs.previous_version
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine
          python -m twine upload dist/*
